### ISSUE TITLE
Transform InjectorGenerator on xxx threw error: Bad state: AnalysisOptions of SDK context cannot be changed.

### ISSUE THREAD

**Issue by Ivanzar** [angular/di.dart#245]
Help, please. I don't know what not work. All crash when I add di to transforms.

I clear all code, but not work.

```yaml
name: 'untitled3'
version: 0.0.1
description: An absolute bare-bones web app.
#author: ivan <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  my_dependency: any

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

  js: ^0.6.0

  logging: any
  logging_handlers: any
  console_log_handler: any

  mdl:
  di: any

  code_transformers:


transformers:
- dart_to_js_script_rewriter
- di
```

```dart
void main() {
}
```

```html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>

<script type="application/dart" src="main.dart"></script>
<script src="packages/browser/dart.js"></script>

</body>
</html>
```

Error:

```
Build error:
Transform InjectorGenerator on untitled3|web/main.dart threw error: Bad state: AnalysisOptions of SDK context cannot be changed.
package:analyzer/src/context/context.dart 2287       SdkAnalysisContext.analysisOptions=
package:code_transformers/src/resolver_impl.dart 64  ResolverImpl.ResolverImpl
package:code_transformers/src/resolvers.dart 60      Resolvers.get.<fn>
dart:collection-patch/compact_hash.dart 265          _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent
package:code_transformers/src/resolvers.dart 59      Resolvers.get
package:code_transformers/src/resolvers.dart 113     Transformer&ResolverTransformer.applyToEntryPoints
package:code_transformers/src/resolvers.dart 101     Transformer&ResolverTransformer.apply.<fn>
dart:async/zone.dart 1404                            _RootZone.runUnary
dart:async/future_impl.dart 131                      _FutureListener.handleValue
dart:async/future_impl.dart 637                      _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 667                      _Future._propagateToListeners
dart:async/future_impl.dart 477                      _Future._completeWithValue
dart:async/future_impl.dart 528                      _Future._asyncComplete.<fn>
dart:async/schedule_microtask.dart 41                _microtaskLoop
dart:async/schedule_microtask.dart 50                _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 96             _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149            _RawReceivePortImpl._handleMessage

package:analyzer/src/context/context.dart 2287       SdkAnalysisContext.analysisOptions=
package:code_transformers/src/resolver_impl.dart 64  ResolverImpl.ResolverImpl
package:code_transformers/src/resolvers.dart 60      Resolvers.get.<fn>
dart:collection                                      _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent
package:code_transformers/src/resolvers.dart 59      Resolvers.get
package:code_transformers/src/resolvers.dart 113     Transformer&ResolverTransformer.applyToEntryPoints
package:code_transformers/src/resolvers.dart 101     Transformer&ResolverTransformer.apply.<fn>
Build completed with 1 errors.
[web] GET index.html => untitled3|web/index.html
[web] GET main.dart => Could not find asset untitled3|web/main.dart.
[web] GET packages/browser/dart.js => (cached) browser|lib/dart.js
[web] GET main.dart.js => Could not find asset untitled3|web/main.dart.js.

```
